default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: my_development_database_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_test_database_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_production_database_development
  pool: 5
  timeout: 5000
